version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Eslint
          command: yarn run eslint --fix .
      - run:
          name: Prettier
          command: yarn prettier --write .
