version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Eslint
          command: yarn eslint
      - run:
          name: Prettier
          command: yarn prettier --write "**/*.{js,jsx}"
