enum DefaultFieldKey {
  ADDRESS = "address",
  CELL_NUMBER = "cell_number",
  CHILDREN = "children",
  GUESTS = "guests",
  DATE_OF_BIRTH = "date_of_birth",
  ENROLLED_CLASS = "enrolled_class",
  EMAIL = "email",
  FIRST_NAME = "first_name",
  HOME_NUMBER = "home_number",
  ID = "id",
  LAST_NAME = "last_name",
  NOTES = "notes",
  NUM_CHILDREN = "num_children",
  PHONE_NUMBER = "phone_number",
  PREFERRED_CLASS = "preferred_class",
  PREFERRED_CONTACT = "preferred_comms",
  PREFERRED_NUMBER = "preferred_number",
  REGISTERED_AT = "registered_at",
  SESSION = "session",
  STATUS = "status",
  WORK_NUMBER = "work_number",
}

export default DefaultFieldKey;
